backend:
  name: github
  repo: rymate1234/rymate.co.uk
  branch: master    # Branch to update
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "URL", name: "url", widget: "hidden"}

  - name: "project" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "content/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Type", name: "type", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Source Code", name: "source", widget: "string"}
      - {label: "Project Site", name: "site", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - label: "Status"
        name: "status"
        widget: "select"
        options: ["active", "inactive", "legacy"]
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "URL", name: "url", widget: "hidden"}
